# Generated by Django 3.1.7 on 2021-03-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
