# Generated by Django 3.1.7 on 2021-03-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
    ]
